language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer install --dev --prefer-source --no-interaction

script:
#  - vendor/bin/phpspec run
  - php -l ./**/*.php # Sceptic whether Travis Supports globbing like this, but it's worth a shot.
