language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer install --dev --prefer-source --no-interaction

script:
#  - vendor/bin/phpspec run
  - php -l ./src/Webhook.php
  - php -l ./src/WebhookInterface.php
  - php -l ./src/Deployer.php
  - php -l ./src/GithubDeployer.php
